// Benchmark harness for `analytics_toolkit`. Not part of the
// published package; lives under `bench/` at the package root and is
// invoked via `dart run bench/bench_runner.dart` before a release.
//
// Each scenario file under `scenarios/` exports a function returning a
// `Future<BenchResult>` for a given record count. This runner invokes
// every scenario at three record counts (10,000 / 100,000 / 1,000,000)
// and writes one Markdown table per scenario to stdout. Progress lines
// go to stderr so the captured stdout is paste-ready:
//
//   dart run bench/bench_runner.dart > bench_results.md
//
// The Markdown tables go directly into the README's Performance
// section.
//
// Each scenario does:
//   1. Generate synthetic SourceRecords deterministically (seeded RNG).
//   2. Build the query for the scenario.
//   3. Run AnalyticsExecutor.execute once as a warmup.
//   4. Run it 10 more times timed, collecting wall-time microseconds.
//   5. Return median / p95 / p99 over the timed samples.

// ignore_for_file: avoid_print

import 'dart:io';

import 'package:analytics_toolkit/analytics_toolkit.dart';

import 'scenarios/calculated_measure.dart' as calculated_measure;
import 'scenarios/derived_operations.dart' as derived_operations;
import 'scenarios/multi_measure_aggregation.dart' as multi_measure_aggregation;
import 'scenarios/multi_series_aggregation.dart' as multi_series_aggregation;
import 'scenarios/series_aggregation.dart' as series_aggregation;
import 'scenarios/streak.dart' as streak;
import 'scenarios/time_grouped_densified.dart' as time_grouped_densified;

// ── Public API used by scenarios ────────────────────────────────────────────

/// Wall-time percentiles over 10 timed runs of one scenario at one
/// record count.
class BenchResult {
  const BenchResult({
    required this.medianMicros,
    required this.p95Micros,
    required this.p99Micros,
  });

  final int medianMicros;
  final int p95Micros;
  final int p99Micros;
}

/// Runs [op] once as a warmup, then 10 more times timed, and returns
/// the median / p95 / p99 wall time. [op] must execute the full
/// pipeline being measured — generating records and building the query
/// happen outside this function.
BenchResult timeRuns(void Function() op) {
  // Warmup — discarded.
  op();

  final samples = <int>[];
  for (var i = 0; i < 10; i++) {
    final sw = Stopwatch()..start();
    op();
    sw.stop();
    samples.add(sw.elapsedMicroseconds);
  }
  samples.sort();

  return BenchResult(
    medianMicros: _percentileMicros(samples, 50),
    p95Micros: _percentileMicros(samples, 95),
    p99Micros: _percentileMicros(samples, 99),
  );
}

/// Asserts that [result] is `Ok`; throws `StateError` otherwise.
///
/// Scenarios call this on every `AnalyticsExecutor.execute` result to
/// surface bench setup bugs (a query that fails to validate, a record
/// with the wrong typed value, etc.) loudly rather than letting the
/// bench silently measure error short-circuits.
void requireOk(Result<AnalyticsResult, AnalyticsError> result) {
  switch (result) {
    case Ok():
      return;
    case Err(error: final e):
      throw StateError('Bench execute failed: ${e.humanMessage}');
  }
}

// ── Runner ──────────────────────────────────────────────────────────────────

const _recordCounts = [10000, 100000, 1000000];

Future<void> main(List<String> args) async {
  stderr.writeln('Running benchmarks (warmup + 10 timed runs each).');
  stderr.writeln('Record counts per scenario: ${_recordCounts.join(", ")}.');
  stderr.writeln('Markdown tables go to stdout; progress goes here.');
  stderr.writeln('');

  // Emit environment lines once at the top so the captured output
  // carries its own provenance when pasted into the README.
  print('<!-- Generated by `dart run bench/bench_runner.dart`. -->');
  print('<!-- CPU: ${_detectCpuModel()} -->');
  print('<!-- Dart: ${Platform.version} -->');
  print(
    '<!-- OS: ${Platform.operatingSystem} '
    '${Platform.operatingSystemVersion} -->',
  );
  print('<!-- Processors: ${Platform.numberOfProcessors} -->');

  await _runScenario(
    'series_aggregation',
    (n) => series_aggregation.run(recordCount: n),
  );
  await _runScenario(
    'multi_series_aggregation',
    (n) => multi_series_aggregation.run(recordCount: n),
  );
  await _runScenario(
    'multi_measure_aggregation',
    (n) => multi_measure_aggregation.run(recordCount: n),
  );
  await _runScenario(
    'calculated_difference',
    (n) => calculated_measure.runDifference(recordCount: n),
  );
  await _runScenario(
    'calculated_nested',
    (n) => calculated_measure.runNested(recordCount: n),
  );
  await _runScenario(
    'time_grouped_densified',
    (n) => time_grouped_densified.run(recordCount: n),
  );
  await _runScenario(
    'time_grouped_sparse',
    (n) => time_grouped_densified.runSparse(recordCount: n),
  );
  await _runScenario('streak', (n) => streak.run(recordCount: n));
  await _runScenario(
    'derived_cumulative_sum',
    (n) => derived_operations.runCumulativeSum(recordCount: n),
  );
  await _runScenario(
    'derived_delta',
    (n) => derived_operations.runDelta(recordCount: n),
  );
  await _runScenario(
    'derived_moving_average_window_7',
    (n) => derived_operations.runMovingAverage(recordCount: n),
  );

  stderr.writeln('');
  stderr.writeln('Done.');
}

Future<void> _runScenario(
  String name,
  Future<BenchResult> Function(int recordCount) run,
) async {
  stderr.writeln('▸ $name');
  print('');
  print('## $name');
  print('');
  print('| records   | median    | p95       | p99       |');
  print('| --------- | --------- | --------- | --------- |');
  for (final count in _recordCounts) {
    stderr.write('  ${_formatCount(count)} records ... ');
    final result = await run(count);
    stderr.writeln('${_formatMicros(result.medianMicros)} median');
    print(
      '| ${_formatCount(count).padRight(9)} '
      '| ${_formatMicros(result.medianMicros).padRight(9)} '
      '| ${_formatMicros(result.p95Micros).padRight(9)} '
      '| ${_formatMicros(result.p99Micros).padRight(9)} |',
    );
  }
}

// ── Formatting helpers ──────────────────────────────────────────────────────

/// Formats an integer with comma thousands separators.
String _formatCount(int n) {
  final s = n.abs().toString();
  final buf = StringBuffer(n < 0 ? '-' : '');
  for (var i = 0; i < s.length; i++) {
    if (i > 0 && (s.length - i) % 3 == 0) buf.write(',');
    buf.write(s[i]);
  }
  return buf.toString();
}

/// Formats a microsecond count as a short human-readable duration.
///
/// Scale-aware: sub-millisecond results show two decimals in ms;
/// sub-100ms one decimal; sub-10s rounded ms; beyond that, seconds.
String _formatMicros(int micros) {
  final ms = micros / 1000.0;
  if (ms < 1.0) return '${ms.toStringAsFixed(2)} ms';
  if (ms < 100.0) return '${ms.toStringAsFixed(1)} ms';
  if (ms < 10000.0) return '${ms.round()} ms';
  return '${(ms / 1000.0).toStringAsFixed(1)} s';
}

// ── Percentile helper ───────────────────────────────────────────────────────

/// Returns the [p]-th percentile of a pre-sorted [sortedSamples] list,
/// using linear interpolation between closest ranks. Caller must pass
/// a non-empty already-sorted list.
int _percentileMicros(List<int> sortedSamples, double p) {
  if (sortedSamples.isEmpty) {
    throw StateError('percentile called on empty sample list');
  }
  if (sortedSamples.length == 1) return sortedSamples.first;
  final rank = (p / 100) * (sortedSamples.length - 1);
  final lower = rank.floor();
  final upper = rank.ceil();
  if (lower == upper) return sortedSamples[lower];
  final frac = rank - lower;
  final lowerVal = sortedSamples[lower].toDouble();
  final upperVal = sortedSamples[upper].toDouble();
  return (lowerVal * (1 - frac) + upperVal * frac).round();
}

// ── CPU model detection ─────────────────────────────────────────────────────

/// Returns the host CPU model string for the bench provenance comment.
///
/// Dart's `Platform` doesn't expose the CPU model, so each OS gets its
/// own shell-out:
/// * macOS — `sysctl -n machdep.cpu.brand_string`
/// * Linux — first `model name` line from `/proc/cpuinfo`
/// * Windows — `Name=...` line from `wmic cpu get name /value`
///
/// Any failure (process not found, non-zero exit, empty output)
/// degrades to `"unknown"`. The CPU model is useful provenance for the
/// README's Performance section, so we emit something rather than
/// silently dropping the line.
String _detectCpuModel() {
  try {
    if (Platform.isMacOS) {
      final r = Process.runSync('sysctl', const [
        '-n',
        'machdep.cpu.brand_string',
      ]);
      if (r.exitCode == 0) {
        final out = (r.stdout as String).trim();
        if (out.isNotEmpty) return out;
      }
    } else if (Platform.isLinux) {
      final file = File('/proc/cpuinfo');
      if (file.existsSync()) {
        for (final line in file.readAsLinesSync()) {
          if (line.startsWith('model name')) {
            final idx = line.indexOf(':');
            if (idx >= 0 && idx + 1 < line.length) {
              final name = line.substring(idx + 1).trim();
              if (name.isNotEmpty) return name;
            }
          }
        }
      }
    } else if (Platform.isWindows) {
      final r = Process.runSync('wmic', const ['cpu', 'get', 'name', '/value']);
      if (r.exitCode == 0) {
        for (final line in (r.stdout as String).split('\n')) {
          final t = line.trim();
          if (t.startsWith('Name=')) {
            final name = t.substring('Name='.length).trim();
            if (name.isNotEmpty) return name;
          }
        }
      }
    }
  } catch (_) {
    // Any failure → unknown; intentional so bench never blocks on
    // provenance detection.
  }
  return 'unknown';
}
